query ProductsIdView($productId: ID!) {
  product(productId: $productId) {
    id
    name
    description
    priceCurrency
    priceValue
    pictures {
      id
      createdAt
      updatedAt
      hash # https://blurha.sh/
      height
      width
      mimetype
      originalName
      size
      url
    }
    owner {
      id
      firstName
      lastName
      ...OwnedProducts
    }
  }
}